<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrJXhTm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrJXhTm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUrJXhTm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUrJXhTm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUrJXhTm\App_KernelDevDebugContainer([
    'container.build_hash' => 'UrJXhTm',
    'container.build_id' => 'be27eae1',
    'container.build_time' => 1748282812,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrJXhTm');
