security:
    # Override access control for development environment
    access_control:
        - { path: ^/api/auth/(login|register), roles: PUBLIC_ACCESS }
        - { path: ^/health, roles: PUBLIC_ACCESS }
        - { path: ^/api/test, roles: PUBLIC_ACCESS }  # Public in development
        - { path: ^/api/auth, roles: ROLE_USER }
        - { path: ^/api, roles: PUBLIC_ACCESS } 